import { generateEnvContent, parseEnvContent } from './generator';
import { PortConfig } from '../config/schema';

const mockConfig: PortConfig = {
  version: 1,
  ports: {
    api: 3000,
    web: 8080,
    db: 5432,
  },
  profiles: {
    dev: {
      ports: {
        api: 4000,
        web: 9090,
      },
    },
  },
  activeProfile: undefined,
};

describe('generateEnvContent', () => {
  it('generates env content from base ports', () => {
    const content = generateEnvContent(mockConfig);
    expect(content).toContain('API=3000');
    expect(content).toContain('WEB=8080');
    expect(content).toContain('DB=5432');
  });

  it('uses active profile ports when set', () => {
    const config = { ...mockConfig, activeProfile: 'dev' };
    const content = generateEnvContent(config);
    expect(content).toContain('API=4000');
    expect(content).toContain('WEB=9090');
    expect(content).not.toContain('DB=');
  });

  it('applies prefix option', () => {
    const content = generateEnvContent(mockConfig, { prefix: 'PORT_' });
    expect(content).toContain('PORT_API=3000');
    expect(content).toContain('PORT_WEB=8080');
  });

  it('respects uppercase: false option', () => {
    const content = generateEnvContent(mockConfig, { uppercase: false });
    expect(content).toContain('api=3000');
    expect(content).toContain('web=8080');
  });

  it('includes a generated header comment', () => {
    const content = generateEnvContent(mockConfig);
    expect(content).toContain('# Generated by portkey');
  });
});

describe('parseEnvContent', () => {
  it('parses key=value pairs', () => {
    const content = 'API=3000\nWEB=8080\n';
    const result = parseEnvContent(content);
    expect(result).toEqual({ API: '3000', WEB: '8080' });
  });

  it('ignores comment lines', () => {
    const content = '# comment\nAPI=3000\n';
    const result = parseEnvContent(content);
    expect(result).toEqual({ API: '3000' });
  });

  it('ignores blank lines', () => {
    const content = '\nAPI=3000\n\nWEB=8080\n';
    const result = parseEnvContent(content);
    expect(result).toEqual({ API: '3000', WEB: '8080' });
  });

  it('returns empty object for empty content', () => {
    expect(parseEnvContent('')).toEqual({});
  });
});
