import { PortConfig } from '../config/schema';

export interface EnvGeneratorOptions {
  prefix?: string;
  uppercase?: boolean;
}

const DEFAULT_OPTIONS: EnvGeneratorOptions = {
  prefix: '',
  uppercase: true,
};

/**
 * Generates a .env file content string from a port configuration.
 */
export function generateEnvContent(
  config: PortConfig,
  options: EnvGeneratorOptions = {}
): string {
  const opts = { ...DEFAULT_OPTIONS, ...options };
  const lines: string[] = [
    `# Generated by portkey`,
    `# Profile: ${config.activeProfile ?? 'default'}`,
    `# Generated at: ${new Date().toISOString()}`,
    '',
  ];

  const profile = config.activeProfile
    ? config.profiles?.[config.activeProfile]
    : null;

  const ports = profile?.ports ?? config.ports ?? {};

  for (const [name, port] of Object.entries(ports)) {
    let key = opts.prefix ? `${opts.prefix}${name}` : name;
    if (opts.uppercase) {
      key = key.toUpperCase();
    }
    lines.push(`${key}=${port}`);
  }

  return lines.join('\n') + '\n';
}

/**
 * Parses an existing .env file content into a key-value map.
 */
export function parseEnvContent(content: string): Record<string, string> {
  const result: Record<string, string> = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIndex = trimmed.indexOf('=');
    if (eqIndex === -1) continue;
    const key = trimmed.slice(0, eqIndex).trim();
    const value = trimmed.slice(eqIndex + 1).trim();
    result[key] = value;
  }
  return result;
}
